### PR TITLE
Fix for 2 vulnerable dependency paths

### PR DESCRIPTION
**Pull request by snyk-community**
bower-art-resolver currently has a 2 vulnerable dependency paths, introducing 2 different types of known vulnerabilities.

This PR fixes vulnerable dependencies.
- [ReDOS vulnerability](https://snyk.io/vuln/npm:hawk:20160119) in the `hawk` dependency.
- [remote memory exposure ](https://snyk.io/vuln/npm:request:20160119) vulnerability in the `request` dependency.

You can see [Snyk test report](https://snyk.io/test/github/JFrogDev/bower-art-resolver) of this project for details. 

This PR changes `Package.json` to upgrade `request` to the newer 2.74.0 version, and will fix all the vulnerabilities.

You can get alerts and fix PRs for future vulnerabilities for free by [watching this repo with Snyk](https://snyk.io/add).

Stay Secure,
The Snyk Team

### CODE REVIEW

**Comment by eyalbe4** [comment]
@snyk-community, thank you for this PR!
Can you please sign [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge this?

**Comment by prycec** [comment]
Is there a plan to merge this change soon ?

**Comment by eyalbe4** [comment]
@prycec, since we can't merge this pull request, we'll soon implement this through a different commit.

**Comment by eyalbe4** [comment]
@prycec and @snyk-community,
Version 2.0.8 of the bower-art-resolver package includes the change.

**Pull request closed without merging**
