### PR TITLE
stop displaying auth information in errors

### PR DESCRIPTION
**Pull request by mithun**

### CODE REVIEW

**Comment by mithun** [comment]
@eyalbe4 can you please review this?

**Comment by eyalbe4** [comment]
Sure thing. Thank you for this @mithun! Will review this soon.

**Comment by mithun** [comment]
Is it possible to use API keys instead of username:encryptedpassword in the registry URL?

**Comment by eyalbe4** [comment]
Hi @mithun, 
Currently API keys are not supported, but we would like to support this in the future.
I looked at your PR, and the code you added indeed removes the authentication information from the Artifactory URL used for the log print, but please note that the URL cleanup does not apply for all scenarios. For example, if your Artifactory instance is not accessible (try to configure the wrong port for example), you'll still see the URL as is in the error message. This is because that error print is not part of the resolver code. Please let me know what you think.

**Comment by mithun** [comment]
@eyalbe4 I agree this will not apply to errors outside of bower-art-resolver (e.g., `request` can error out directly).

Ideally, I think credentials (user/password OR API key) should be stored in the `.bowerrc` in a bower-art-resolver specific configuration tree and not part of the URL. bower-art-resolver should construct an appropriate request using those configurations.

**Comment by eyalbe4** [comment]
@mithun, since the authentication details removal is not complete (as discussed above), I suggest we don't add this code for now. Maybe authentication details for resolver is something that should be supported by the .bowerrc specification. With your permission, I'll close this issue.

**Comment by mithun** [comment]
@eyalbe4 sounds good.

**Pull request closed without merging**
